<MenuWidget>:
    canvas.before:
        Color:
            rgba: 0,0,0,.8
        Rectangle:
            size: self.size
    Label:
        text:"Choose the button below that you want to click"
        pos_hint:{"center_x":.5,"center_y":.6}
    Button:
        text:"Start"
        pos_hint:{"center_x":.3,"center_y":.4,"left":.6}
        size_hint:.2,.1
    Button:
        text:"Exit"
        pos_hint:{"center_x":.3,"center_y":.4,"right":.8}
        size_hint:.2,.1
